load_anns <- function() {
  ann_incisor_1_DC1    <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_incisor_1_DC1.rda")
  ann_canine_1_DC1     <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_canine_1_DC1.rda")
  ann_premolar_1_DC1   <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_premolar_1_DC1.rda")
  ann_molar_1_DC1      <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_molar_1_DC1.rda")
  ann_incisor_12_DC1   <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_incisor_12_DC1.rda")
  ann_canine_12_DC1    <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_canine_12_DC1.rda")
  ann_premolar_12_DC1  <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_premolar_12_DC1.rda")
  ann_molar_12_DC1     <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_molar_12_DC1.rda")
  ann_incisor_12_DC2   <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_incisor_12_DC2.rda")
  ann_canine_12_DC2    <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_canine_12_DC2.rda")
  ann_premolar_12_DC2  <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_premolar_12_DC2.rda")
  ann_molar_12_DC2     <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_molar_12_DC2.rda")
  ann_incisor_123_DC1  <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_incisor_123_DC1.rda")
  ann_canine_123_DC1   <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_canine_123_DC1.rda")
  ann_premolar_123_DC1 <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_premolar_123_DC1.rda")
  ann_molar_123_DC1    <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_molar_123_DC1.rda")
  ann_incisor_123_DC2  <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_incisor_123_DC2.rda")
  ann_canine_123_DC2   <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_canine_123_DC2.rda")
  ann_premolar_123_DC2 <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_premolar_123_DC2.rda")
  ann_molar_123_DC2    <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_molar_123_DC2.rda")
  ann_incisor_123_DC3  <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_incisor_123_DC3.rda")
  ann_canine_123_DC3   <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_canine_123_DC3.rda")
  ann_premolar_123_DC3 <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_premolar_123_DC3.rda")
  ann_molar_123_DC3    <- readRDS("https://github.com/paleomariomm/teethR/tree/master/ann_models/ann_molar_123_DC3.rda")
}
